[s3]
  bucketname = "tap1"
  conversationspath = "conversations"

[sqs]
  inboxURL = "https://sqs.eu-west-2.amazonaws.com/049513327431/TA-inbox"
  outboxURL = "https://sqs.eu-west-2.amazonaws.com/049513327431/TA-outbox"

[log]
  fileout = false
  level = "info"
  logfilepath = "/logs"
  stdout = true
  jsonformat = false
 
