
[general]

[s3]
  bucketname = "tap1"
  conversationspath = "conversations"


[sqs]
  inboxURL = "https://sqs.eu-west-2.amazonaws.com/049513327431/TAP1-Inbox"
  outboxURL = "https://sqs.eu-west-2.amazonaws.com/049513327431/TAP1-Outbox"


[log]
  fileout = false
  level = "info"
  logfilepath = "/tmp"
  stdout = true
  jsonformat = false

